steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/application-master:$COMMIT_SHA', '.']
  dir: './source/application/'
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/application-master:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'application-master'
  - '--image'
  - 'gcr.io/$PROJECT_ID/application-master:$COMMIT_SHA'
  - '--cluster'
  - 'standard-cluster-1'
  - '--cluster-location'
  - 'us-west1-a'
  - '--platform'
  - 'gke'
  - '--set-env-vars'
  - 'NODE_ENV=production'
  - '--port'
  - '80'
images:
- 'gcr.io/$PROJECT_ID/application-master:$COMMIT_SHA'
