# docker-compose.yml
version: "3"

services:
  node-nodemon:
    depends_on:
      - "mariadb"
    image: "node:12.15.0"
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      NODE_ENV: "development"
      DB_HOST: "mariadb"
      DB_DATABASE: "team103"
      DB_USER: "team103"
      DB_PASS: "team103"
    working_dir: /home/node/app/
    volumes:
      - .:/home/node/app/:ro
      - ./node_modules/:/home/node/app/node_modules/:ro
    command: "npm run start-watch"
  node-ava:
    depends_on:
      - "node-nodemon"
    image: "node:12.15.0"
    user: "node"
    environment:
      NODE_ENV: "development"
      DB_HOST: "mariadb"
      DB_DATABASE: "team103"
      DB_USER: "team103"
      DB_PASS: "team103"
    working_dir: /home/node/app/
    volumes:
      - .:/home/node/app/
      - ./node_modules/:/home/node/app/node_modules/:ro
    command: "npm run test-watch"
  mariadb:
    image: "mariadb:10.4.12"
    ports:
      - "3306:3306"
    environment:
      MYSQL_INITDB_SKIP_TZINFO: "1"
      MYSQL_ROOT_PASSWORD: "team103"
      MYSQL_USER: "team103"
      MYSQL_PASSWORD: "team103"
      MYSQL_DATABASE: "team103"
    volumes:
      - mariadb:/var/lib/mysql/

volumes:
  mariadb:
