name: Node.js - application

on:
  push:
    paths:
      - '.github/workflows/node-application.yml'
      - 'source/application/*'
  pull_request:
    types: [opened, edited, reopened, synchronize]
    paths:
      - '.github/workflows/node-application.yml'
      - 'source/application/*'
  check_run:
    types: [created, rerequested, requested_action]
    paths:
      - '.github/workflows/node-application.yml'
      - 'source/application/*'

jobs:
  application-ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
        working-directory: source/application/
      - run: npm test
        working-directory: source/application/
